name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: publish
      run: |
        git config --global user.email "hacksore@users.noreply.github.com"
        git config --global user.name "Sean Boult"
        echo "machine github.com login Hacksore password $GH_TOKEN" > ~/.netrc
        cd website && yarn install && GIT_USER=Hacksore yarn run publish-gh-pages